---
- name: playbook_docker.yml - docker and stuff
  hosts: all
  become: yes

  tasks:
    - name: install docker compose
      apt:
        update_cache: yes
        name:
          - docker-compose

    - name: add the user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Create /etc/docker directory if it does not exist
      file:
        path: /etc/docker
        state: directory
        mode: '0755'

    - name: set default max logs size to 250MB and set logs rotation
      copy:
        dest: '/etc/docker/daemon.json'
        content: |
          {
            "log-driver": "json-file",
            "log-opts": {
              "max-size": "50m",
              "max-file": "5"
            }
          }

    - name: Download ctop binary and make it executable
      get_url:
        url: "https://github.com/bcicen/ctop/releases/download/v0.7.7/ctop-0.7.7-linux-amd64"
        dest: "/usr/local/bin/ctop"
        mode: '0755'
